title: JSONassertify
description: "Write JSON unit tests in less code.  Great for testing REST interfaces."

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme 

# Navigation links
nav:
  - title: "Code Coverage"
    url: "https://app.codecov.io/gh/UnitVectorY-Labs/JSONassertify"
