title: JSONassertify
description: "Write JSON unit tests in less code.  Great for testing REST interfaces."

remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme

# Aux links for the upper right navigation
aux_links:
  "JSONassertify on GitHub":
    - "https://github.com/UnitVectorY-Labs/JSONassertify"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/UnitVectorY-Labs/JSONassertify"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"

# Navigation links
nav_external_links:
  - title: Java Docs
    url: https://javadoc.io/doc/com.unitvectory/jsonassertify/latest/index.html
    opens_in_new_tab: true
  - title: Maven Central
    url: https://central.sonatype.com/artifact/com.unitvectory/jsonassertify
    opens_in_new_tab: true

